definitions:
  request.MeGet:
    type: object
  resource.Error:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  response.Me:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      gender:
        type: string
      id:
        type: integer
      nickName:
        type: string
      randID:
        type: string
      updatedAt:
        type: string
    type: object
  response.MeGet:
    properties:
      me:
        $ref: '#/definitions/response.Me'
        type: object
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/me:
    get:
      consumes:
      - application/json
      parameters:
      - description: Request body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.MeGet'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.MeGet'
        "500":
          description: something went wrong
          schema:
            $ref: '#/definitions/resource.Error'
      summary: 自分の情報を取得
swagger: "2.0"
