// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InvitedUser struct {
	RoomName             string   `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvitedUser) Reset()         { *m = InvitedUser{} }
func (m *InvitedUser) String() string { return proto.CompactTextString(m) }
func (*InvitedUser) ProtoMessage()    {}
func (*InvitedUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *InvitedUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvitedUser.Unmarshal(m, b)
}
func (m *InvitedUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvitedUser.Marshal(b, m, deterministic)
}
func (m *InvitedUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvitedUser.Merge(m, src)
}
func (m *InvitedUser) XXX_Size() int {
	return xxx_messageInfo_InvitedUser.Size(m)
}
func (m *InvitedUser) XXX_DiscardUnknown() {
	xxx_messageInfo_InvitedUser.DiscardUnknown(m)
}

var xxx_messageInfo_InvitedUser proto.InternalMessageInfo

func (m *InvitedUser) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *InvitedUser) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Coordinate           *Coordinate `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCoordinate() *Coordinate {
	if m != nil {
		return m.Coordinate
	}
	return nil
}

type Coordinate struct {
	Longitude            float64  `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Coordinate) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*InvitedUser)(nil), "rpc.InvitedUser")
	proto.RegisterType((*User)(nil), "rpc.User")
	proto.RegisterType((*Coordinate)(nil), "rpc.Coordinate")
	proto.RegisterType((*Empty)(nil), "rpc.Empty")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x14, 0xc4, 0x4d, 0x8d, 0x7f, 0x32, 0x39, 0x28, 0xef, 0x54, 0x8a, 0x42, 0xd9, 0x83, 0xf4, 0x14,
	0xa1, 0xe2, 0x27, 0x10, 0xa5, 0x2a, 0x78, 0x08, 0xf8, 0x01, 0x62, 0xb2, 0xc8, 0x42, 0xb2, 0x6f,
	0x79, 0xdd, 0x0a, 0x7e, 0x7b, 0xd9, 0x57, 0x49, 0x72, 0xdb, 0x37, 0xb3, 0xf3, 0x63, 0x18, 0xe0,
	0xb0, 0xb7, 0x52, 0x05, 0xe1, 0xc8, 0x74, 0x2a, 0xa1, 0x35, 0x3b, 0x94, 0xaf, 0xfe, 0xc7, 0x45,
	0xdb, 0x7d, 0xee, 0xad, 0xd0, 0x0a, 0x97, 0xc2, 0x3c, 0x7c, 0x34, 0x83, 0x5d, 0x66, 0xeb, 0x6c,
	0x53, 0xd4, 0xe3, 0x4d, 0xb7, 0xc8, 0x53, 0x7a, 0xb9, 0x58, 0x67, 0x9b, 0x72, 0x5b, 0x54, 0x12,
	0xda, 0x2a, 0x85, 0x6a, 0x95, 0xcd, 0x3b, 0x72, 0x45, 0x10, 0x72, 0x3f, 0xc5, 0xf5, 0x4d, 0xf7,
	0x40, 0xcb, 0x2c, 0x9d, 0xf3, 0x4d, 0xb4, 0xff, 0x80, 0x2b, 0x05, 0x3c, 0x8d, 0x72, 0x3d, 0xfb,
	0x62, 0x5e, 0x80, 0xc9, 0xa1, 0x1b, 0x14, 0x3d, 0xfb, 0x6f, 0x17, 0x0f, 0xdd, 0x91, 0x9b, 0xd5,
	0x93, 0x90, 0x3a, 0xf7, 0x4d, 0x3c, 0x9a, 0x0b, 0x35, 0xc7, 0xdb, 0x5c, 0xe0, 0xec, 0x79, 0x08,
	0xf1, 0x77, 0xfb, 0x88, 0x32, 0xb5, 0xdb, 0x35, 0xbe, 0xeb, 0xad, 0xd0, 0x1d, 0xf2, 0x37, 0x76,
	0x9e, 0xae, 0xb5, 0xc4, 0x6c, 0x81, 0x15, 0x54, 0xd1, 0x90, 0x39, 0xf9, 0x3a, 0xd7, 0xa9, 0x1e,
	0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xff, 0xa2, 0x10, 0x3c, 0x38, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserHandlerClient is the client API for UserHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserHandlerClient interface {
	Join(ctx context.Context, in *InvitedUser, opts ...grpc.CallOption) (*Empty, error)
}

type userHandlerClient struct {
	cc *grpc.ClientConn
}

func NewUserHandlerClient(cc *grpc.ClientConn) UserHandlerClient {
	return &userHandlerClient{cc}
}

func (c *userHandlerClient) Join(ctx context.Context, in *InvitedUser, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rpc.UserHandler/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserHandlerServer is the server API for UserHandler service.
type UserHandlerServer interface {
	Join(context.Context, *InvitedUser) (*Empty, error)
}

// UnimplementedUserHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedUserHandlerServer struct {
}

func (*UnimplementedUserHandlerServer) Join(ctx context.Context, req *InvitedUser) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}

func RegisterUserHandlerServer(s *grpc.Server, srv UserHandlerServer) {
	s.RegisterService(&_UserHandler_serviceDesc, srv)
}

func _UserHandler_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvitedUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.UserHandler/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).Join(ctx, req.(*InvitedUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.UserHandler",
	HandlerType: (*UserHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _UserHandler_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
